version: "3.6"
services:
  freenet:
    container_name: freenet
    image: freenet:x86-alpine-openjdk12-01497-oni
    restart: no
    #network_mode: "host"
    network_mode: "bridge"
    ports:
      - "8888:8888"
      - "9481:9481"
      - "12345:12345/udp"
      - "12346:12346/udp"
    volumes:
      - freenet_conf:/home/fred/conf
      - freenet_data:/home/fred/data
#     Problems with access when using real directories
#      - "/mnt/freenet-data/conf:/home/fred/conf:rw"
#      - "/mnt/freenet-data/data:/home/fred/data:rw"
    environment:
      - allowedhosts=172.17.0.0/24,127.0.0.1,0:0:0:0:0:0:0:1
      - darknetport=12345
      - opennetport=12346
volumes:
  freenet_conf:
  freenet_data: