version: "3.6"
services:
  freenet:
    container_name: freenet
    image: freenet:arm32v7-ubuntu-18.04-01497-ofi
    restart: unless-stopped
    #network_mode: "host"
    network_mode: "bridge"
    ports:
      - "8888:8888"
      - "9581:9481"
      - "22345:12345/udp"
      - "22346:12346/udp"
    volumes:
      - freenet_conf:/home/fred/conf
      - freenet_data:/home/fred/data
#     Problems with access rights when using real directories
#      - "/mnt/freenet-data/conf:/home/fred/conf:rw"
#      - "/mnt/freenet-data/data:/home/fred/data:rw"
    environment:
      - allowedhosts=172.17.0.0/24,127.0.0.1,192.168.0.105,0:0:0:0:0:0:0:1
      - darknetport=12345
      - opennetport=12346
volumes:
  freenet_conf:
  freenet_data: